category = {"https://www.wildberries.ru/catalog/zhenshchinam/odezhda/bluzki-i-rubashki":
            "https://catalog.wb.ru/catalog/bl_shirts/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/bryuki-i-shorty":
            "https://catalog.wb.ru/catalog/pants/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/verhnyaya-odezhda":
            "https://catalog.wb.ru/catalog/outwear1/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/dzhempery-i-kardigany":
            "https://catalog.wb.ru/catalog/jumpers_cardigans/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/dzhinsy-dzhegginsy":
            "https://catalog.wb.ru/catalog/jeans/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/kombinezony-polukombinezony":
            "https://catalog.wb.ru/catalog/overalls/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/kostyumy":
            "https://catalog.wb.ru/catalog/costumes/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/longslivy":
            "https://catalog.wb.ru/catalog/sweatshirts_hoodies/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/pidzhaki-i-zhakety":
            "https://catalog.wb.ru/catalog/blazers_wamuses/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/platya":
            "https://catalog.wb.ru/catalog/dresses/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/tolstovki":
            "https://catalog.wb.ru/catalog/sweatshirts_hoodies/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/tuniki":
            "https://catalog.wb.ru/catalog/sweatshirts_hoodies/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/futbolki-i-topy":
            "https://catalog.wb.ru/catalog/tops_tshirts1/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda-dlya-doma/halaty":
            "https://catalog.wb.ru/catalog/housewear_root/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/bryuki-i-shorty/shorty":
            "https://catalog.wb.ru/catalog/shorts/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/odezhda/yubki":
            "https://catalog.wb.ru/catalog/skirts/catalog?appType=1&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele/aksessuary":
            "https://catalog.wb.ru/catalog/women_underwear2/catalog?appType=1&subject=478;497;550;551;552;553;2768;3457;4929;6372;6531;7278",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/bandazhi":
            "https://catalog.wb.ru/catalog/women_underwear2/catalog?appType=1&kind=2&subject=369",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele/besshovnoe":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&ext=31103&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/bodi-i-korsety":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&kind=2&subject=74;75;282;2600;2622;2623",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/byustgaltery":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&kind=2&subject=76;2048",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/kolgotki-i-chulki":
            "https://catalog.wb.ru/catalog/women_underwear2/catalog?appType=1&kind=2&subject=212;213;214;218;252;434;757;1061;2535;3807;6632",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/kombinatsii-i-neglizhe":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&kind=2&subject=71;1183;2239",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/komplekty-belya":
            "https://catalog.wb.ru/catalog/women_underwear2/catalog?appType=1&kind=2&subject=165",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/korrektiruyushchee-bele":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&ext=31105&kind=2",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/mayki":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&kind=2&subject=131",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/termobele":
            "https://catalog.wb.ru/catalog/women_underwear2/catalog?appType=1&kind=2&subject=166;1123;2683;2684;2685;2686;2687;2688;2689;2690;2691;2692;2693",
            "https://www.wildberries.ru/catalog/zhenshchinam/bele-i-kupalniki/trusy":
            "https://catalog.wb.ru/catalog/women_underwear1/catalog?appType=1&kind=2&subject=133",
            "https://www.wildberries.ru/catalog/zhenshchinam/bolshie-razmery/bele":
            "https://catalog.wb.ru/catalog/women_bigsize/catalog?appType=1&kind=2&subject=71;74;75;76;131;133;165;166;213;214;282;434;1061;1123;1183;2048;2239;2535;2600;2622;2623;2683;2684;2685;2686;2688;2689;2690;2691;2692;2693"}
